#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend  ugo-frontend
        bind *:80
        mode http
        default_backend ugo-backend
backend ugo-backend
        balance roundrobin
        server 294522-web-01 52.91.135.249:80 check
        server 294522-web-02 52.23.244.198:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart