#!/usr/bin/env bash
# Script that displays the contents of the file `/etc/passwd`.
#   Only displays the username, user id, and user home directory path.

while IFS= read -r psword
do
  echo "$psword" | cut -d ':' -f1,3,6
done < "/etc/passwd"
