#!/usr/bin/env bash
#  Script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=':' read -r name psword uid num detail path bin
do
  echo "The user $name is part of the $num gang,"\
  "lives in $path and rides $bin."\
  "$uid's place is protected by the passcode $psword,"\
  "more info about the user here: $detail"
done < "/etc/passwd"
