#!/usr/bin/env bash
#  Script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=':' read -r name psword uid gid info home shell
do
  echo "The user $name is part of the $gid gang,"\
  "lives in $home and rides $shell."\
  "$uid's place is protected by the passcode $psword,"\
  "more info about the user here: $info"
done < "/etc/passwd"
