#!/usr/bin/env bash
# Script to display the contents of the current directory in list format.
#   The content of the current directory
#   In a list format
#   Where only the part of the name after the first dash is displayed 

list=$(ls)
for x in $list; do
  echo "$x" | cut -d '-' -f2
done
